local_repository(
    name = "emsdk",
    path = "..",
)

load("@emsdk//:deps.bzl", "deps")

deps()

load("@emsdk//:emscripten_deps.bzl", "emscripten_deps")

emscripten_deps()

load("@emsdk//:toolchains.bzl", "register_emscripten_toolchains")

register_emscripten_toolchains(cache = {
     "configuration": ["--wasm64"],
     "targets": [
         "libal",
         "libbulkmemory",
         "libc-debug",
         "libc",
         "libc++-noexcept",
         "libc++abi-debug-noexcept",
         "libc++abi-noexcept",
         "libcompiler_rt",
         "libdlmalloc",
         "libembind-rtti",
         "libGL-getprocaddr",
         "libhtml5",
         "libnoexit",
         "libprintf_long_double-debug",
         "libprintf_long_double",
         "libsockets",
         "libstubs-debug",
     ]
 })
